const actionTypes = Object.freeze({
  //app
  APP_START_UP_COMPLETE: "APP_START_UP_COMPLETE",
  SET_CONTENT_OF_CONFIRM_MODAL: "SET_CONTENT_OF_CONFIRM_MODAL",
  CHANGES_LANGUAGE: "CHANGES_LANGUAGE",

  //user
  ADD_USER_SUCCESS: "ADD_USER_SUCCESS",
  USER_LOGIN_SUCCESS: "USER_LOGIN_SUCCESS",
  USER_LOGIN_FAIL: "USER_LOGIN_FAIL",
  PROCESS_LOGOUT: "PROCESS_LOGOUT",

  //----admin
  //create user
  CREATE_USER_SUCCESS: "CREATE_USER_SUCCESS",
  CREATE_USER_FAILED: "CREATE_USER_FAILED",
  //delete
  FETCH_DELETE_USER_SUCCESS: "FETCH_DELETE_USER_SUCCESS",
  FETCH_DELETE_USER_FAILED: "FETCH_DELETE_USER_FAILED",

  //get details user
  GET_DETAIL_USER_SUCCESS: "GET_DETAIL_USER_SUCCESS",
  GET_DETAIL_USER_FAILED: "GET_DETAIL_USER_FAILED",

  //update user
  UPDATE_USER_SUCCESS: "UPDATE_USER_SUCCESS",
  UPDATE_USER_FAILED: "UPDATE_USER_FAILED",
  //gender
  FETCH_GENDER_START: "FETCH_GENDER_START",
  FETCH_GENDER_SUCCES: "FETCH_GENDER_SUCCES",
  FETCH_GENDER_FAILED: "FETCH_GENDER_FAILED",
  //position
  FETCH_POSITION_SUCCES: "FETCH_POSITION_SUCCES",
  FETCH_POSITION_FAILED: "FETCH_POSITION_FAILED",
  //role
  FETCH_ROLE_SUCCESS: "FETCH_ROLE_SUCCESS",
  FETCH_ROLE_FAILED: "FETCH_ROLE_FAILED",
  //render list user
  FETCH_ALL_USER_SUCCESS: "FETCH_ALL_USER_SUCCESS",
  FETCH_ALL_USER_FAILED: "FETCH_ALL_USER_FAILED",
  //load top doctor
  FETCH_LOAD_TOP_DOCTOR_SUCCESS: "FETCH_LOAD_TOP_DOCTOR_SUCCESS",
  FETCH_LOAD_TOP_DOCTOR_FAILED: "FETCH_LOAD_TOP_DOCTOR_FAILED",

  //get all doctors
  FETCH_LOAD_ALL_DOCTOR_SUCCESS: "FETCH_LOAD_ALL_DOCTOR_SUCCESS",
  FETCH_LOAD_ALL_DOCTOR_FAILED: "FETCH_LOAD_ALL_DOCTOR_FAILED",
  //save detail doctor
  SAVE_DETAILS_DOCTOR_SUCCESS: "SAVE_DETAILS_DOCTOR_SUCCESS",
  SAVE_DETAILS_DOCTOR_FAILED: "SAVE_DETAILS_DOCTOR_FAILED",
  //edit details doctor
  EDIT_DETAILS_DOCTOR_SUCCESS: "EDIT_DETAILS_DOCTOR_SUCCESS",
  EDIT_DETAILS_DOCTOR_FAILED: "EDIT_DETAILS_DOCTOR_FAILED",
  //get detail doctor by id
  GET_DETAIL_DOCTOR_BY_ID_SUCCESS: "GET_DETAIL_DOCTOR_BY_ID_SUCCESS",
  GET_DETAIL_DOCTOR_BY_ID_FAILED: "GET_DETAIL_DOCTOR_BY_ID_FAILED",

  //get all schedule medical
  GET_ALL_HOURS_SUCCESS: "GET_ALL_HOURS_SUCCESS",
  GET_ALL_HOURS_FAILED: "GET_ALL_HOURS_FAILED",

  //create schedule for doctor
  SAVE_SCHEDULE_DOCTOR_SUCCESS: "SAVE_SCHEDULE_DOCTOR_SUCCESS",
  SAVE_SCHEDULE_DOCTOR_FAILED: "SAVE_SCHEDULE_DOCTOR_FAILED",
  //get schedule's doctor by date
  GET_SCHEDULE_DOCTOR_SUCCESS: "GET_SCHEDULE_DOCTOR_SUCCESS",
  GET_SCHEDULE_DOCTOR_FAILED: "GET_SCHEDULE_DOCTOR_FAILED",

  //details doctor
  FETCH_REQUIRED_DOCTOR_DETAIL_SUCCESS: "FETCH_REQUIRED_DOCTOR_DETAIL_SUCCESS",
  FETCH_REQUIRED_DOCTOR_DETAIL_FAILED: "FETCH_REQUIRED_DOCTOR_DETAIL_FAILED",
  //get extra information doctor
  GET_EXTRA_INFO_DOCTOR_SUCCESS: "GET_EXTRA_INFO_SUCCESS",
  GET_EXTRA_INFO_DOCTOR_FAILED: "GET_EXTRA_INFO_FAILED",

  //get profile doctor
  GET_PROFILE_DOCTOR_SUCCESS: "GET_PROFILE_DOCTOR_SUCCESS",
  GET_PROFILE_DOCTOR_FAILED: "GET_PROFILE_DOCTOR_FAILED",
  //create booking examination
  CREATE_BOOKING_EXAMINATION_SUCCESS: "CREATE_BOOKING_EXAMINATION_SUCCESS",
  CREATE_BOOKING_EXAMINATION_FAILED: "CREATE_BOOKING_EXAMINATION_FAILED",

  //verify booking appointment
  VERIFY_BOOKING_APPOINTMENT_SUCCESS: "VERIFY_BOOKING_APPOINTMENT_SUCCESS",
  VERIFY_BOOKING_APPOINTMENT_FAILED: "VERIFY_BOOKING_APPOINTMENT_FAILED",

  //get all specialty
  GET_ALL_SPECIALTY_SUCCESS: "GET_ALL_SPECIALTY_SUCCESS",
  GET_ALL_SPECIALTY_FAILED: "GET_ALL_SPECIALTY_FAILED",
  //delete specialty by id
  DELETE_SPECIALTY_BY_ID_SUCCESS: "DELETE_SPECIALTY_BY_ID_SUCCESS",
  DELETE_SPECIALTY_BY_ID_FAILED: "DELETE_SPECIALTY_BY_ID_FAILED",
  //get all clinic
  GET_ALL_CLINIC_SUCCESS: "GET_ALL_CLINIC_SUCCESS",
  GET_ALL_CLINIC_FAILED: "GET_ALL_CLINIC_FAILED",
  //delete clinic
  DELETE_CLINIC_SUCCESS: "DELETE_CLINIC_SUCCESS",
  DELETE_CLINIC_FAILED: "DELETE_CLINIC_FAILED",
});

export default actionTypes;
